apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
      - name: expiration
        image: hammamioumayma/expiration:latest
        ports:
        - containerPort: 3000
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: micro-app-secrets
              key: JWT_KEY
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: micro-app-secrets
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-srv
spec:
  selector:
    app: expiration
  ports:
  - port: 3000
    targetPort: 3000
