apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: hammamioumayma/orders:latest
        ports:
        - containerPort: 3003
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: micro-app-secrets
              key: JWT_KEY
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: micro-app-secrets
              key: MONGO_URI
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: micro-app-secrets
              key: RABBITMQ_URL
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
  - port: 3003
    targetPort: 3003
