apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: hammamioumayma/payments:latest
        ports:
        - containerPort: 3000
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: micro-app-secrets
              key: JWT_KEY
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: micro-app-secrets
        - name: RABBITMQ_URI
          valueFrom:
            secretKeyRef:
              name: micro-app-secrets
              key: RABBITMQ_URI
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
  - port: 3000
    targetPort: 3000
